const { Sandbox } = require('@e2b/code-interpreter');

/**
 * Spin up an e2b sandbox, clone the repo, and use an AI coding agent
 * to generate a fix for the reported issue.
 *
 * @param  {Object} issue        – The issue payload
 * @param  {Object} triageResult – { decision, confidence, reasoning }
 * @return {Object}              – { branch, summary }
 */
async function runSandboxFix(issue, triageResult) {
    const owner = process.env.GITHUB_OWNER;
    const repo = process.env.GITHUB_REPO;
    const token = process.env.GITHUB_TOKEN;
    const branchName = `self-heal/${Date.now()}-${slugify(issue.title)}`;

    let sandbox;
    try {
        // ── 1. Create sandbox ───────────────────────────────────
        sandbox = await Sandbox.create({
            apiKey: process.env.E2B_API_KEY,
        });

        // ── 2. Clone target repository ──────────────────────────
        await sandbox.runCode(`
import subprocess, os

repo_url = "https://${token}@github.com/${owner}/${repo}.git"
subprocess.run(["git", "clone", repo_url, "/home/user/repo"], check=True)
os.chdir("/home/user/repo")

# Create a new branch for the fix
subprocess.run(["git", "checkout", "-b", "${branchName}"], check=True)
subprocess.run(["git", "config", "user.email", "self-heal-bot@users.noreply.github.com"], check=True)
subprocess.run(["git", "config", "user.name", "Self-Heal Bot"], check=True)
    `);

        // ── 3. Generate the fix with the AI coding agent ────────
        const fixPrompt = buildFixPrompt(issue, triageResult);
        const fixResult = await sandbox.runCode(`
import subprocess, json

# Write the prompt to a file so Claude Code can process it
prompt = """${fixPrompt.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"""

with open("/home/user/fix_prompt.txt", "w") as f:
    f.write(prompt)

# Run Claude Code (or equivalent) in non-interactive mode
result = subprocess.run(
    ["claude", "-p", prompt, "--output-format", "json"],
    capture_output=True, text=True, cwd="/home/user/repo",
    timeout=300
)

print(json.dumps({
    "stdout": result.stdout[:5000],
    "stderr": result.stderr[:2000],
    "returncode": result.returncode
}))
    `);

        // ── 4. Commit & push changes ────────────────────────────
        await sandbox.runCode(`
import subprocess

os.chdir("/home/user/repo")

# Stage all changes
subprocess.run(["git", "add", "-A"], check=True)

# Check if there are changes to commit
status = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
if status.stdout.strip():
    subprocess.run(
        ["git", "commit", "-m", "fix: AI-generated self-healing patch for issue - ${issue.title.replace(/"/g, '')}"],
        check=True
    )
    subprocess.run(["git", "push", "origin", "${branchName}"], check=True)
    print("PUSHED")
else:
    print("NO_CHANGES")
    `);

        const summary = fixResult?.results?.[0]?.text || 'Fix generated by AI coding agent in sandbox.';

        return {
            branch: branchName,
            summary,
        };
    } finally {
        // Always clean up the sandbox
        if (sandbox) {
            try { await sandbox.kill(); } catch { /* noop */ }
        }
    }
}

// ── Helpers ──────────────────────────────────────────────────
function buildFixPrompt(issue, triage) {
    return `You are a software engineer fixing a bug in a repository.

ISSUE TITLE: ${issue.title}
DESCRIPTION: ${issue.description}
STEPS TO REPRODUCE: ${issue.stepsToReproduce || 'N/A'}
EXPECTED BEHAVIOR: ${issue.expectedBehavior || 'N/A'}
ACTUAL BEHAVIOR: ${issue.actualBehavior || 'N/A'}

TRIAGE DECISION: ${triage.decision} (confidence: ${triage.confidence})
TRIAGE REASONING: ${triage.reasoning}

Instructions:
1. Read the codebase in /home/user/repo.
2. Identify the root cause of the issue.
3. Implement a minimal, targeted fix.
4. Run any existing tests to verify the fix does not break anything.
5. If no tests exist, add at least one test covering the fix.
6. Do NOT make unrelated changes.`;
}

function slugify(text) {
    return text
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '')
        .slice(0, 40);
}

module.exports = { runSandboxFix };
